index = ["frutas-y-verduras", "vinos-y-licores/vinos", 
         "vinos-y-licores/whisky", "vinos-y-licores/cervezas",
         "vinos-y-licores/otros-licores", "vinos-y-licores/tequilas",
         "delicatessen/quesos", "delicatessen/carnes-maduradas",
         "delicatessen/encurtidos-pates-y-dulces", "despensa/cafe",
         "despensa/chocolate-te-e-infusiones", "despensa/cereales-avena-y-granolas",
         "despensa/aceites-y-vinagres", "panaderia", 
         "despensa/harinas-y-mezclas-para-preparar", "lacteos-huevos-y-refrigerados/leche-y-derivados",
         "lacteos-huevos-y-refrigerados/carnes-frias-y-embutidos", "lacteos-huevos-y-refrigerados/arepas",
         "lacteos-huevos-y-refrigerados/huevos", "lacteos-huevos-y-refrigerados/yogurt-y-bebidas-lacteas",
         "lacteos-huevos-y-refrigerados/quesos-y-quesitos", "bebidas-pasabocas-y-dulces/bebidas",
         "bebidas-pasabocas-y-dulces/frutos-secos", "bebidas-pasabocas-y-dulces/pasabocas",
         "bebidas-pasabocas-y-dulces/galletas", "pollo-carnes-y-pescado/pescados-y-mariscos",
         "pollo-carnes-y-pescado/carne-de-res", "pollo-carnes-y-pescado/carne-de-cerdo",
         "pollo-carnes-y-pescado/pollo", "limpieza-del-hogar/papel-higienico",
         "limpieza-del-hogar/cocina", "limpieza-del-hogar/implementos-para-la-limpieza",
         "limpieza-del-hogar/cuidado-de-la-ropa", "salud-y-belleza/cuidado-capilar",
         "salud-y-belleza/cuidado-corporal", "salud-y-belleza/drogueria", 
         "salud-y-belleza/cuidado-oral", "salud-y-belleza/higiene-intima",
         "mascotas"    
         ]