sites = ["fruver/verduras", "fruver/frutas", 
         "fruver/tuberculos-bulbos-raices", "farmacia/salud-digestiva",
         "farmacia/salud-digestiva", "farmacia/gripa-y-tos",
         "farmacia/salud-sexual", "farmacia/alivio-del-dolor",
         "farmacia/botiquin-y-primeros-auxilios, farmacia/salud-nutricional",
         "lacteos-y-huevos/huevos", "lacteos-y-huevos/quesos",
         "lacteos-y-huevos/bebidas-lacteas", "lacteos-y-huevos/mantequillas-y-margarinas",
         "snacks-y-pasabocas/papitas", "snacks-y-pasabocas/mix",
         "snacks-y-pasabocas/palomitas", "bebidas/gaseosas",
         "bebidas/agua-natural-y-saborizada", "bebidas/jugos-y-nectares",
         "bebidas/energizantes-e-isotonicos", "bebidas/bebidas-listas-y-en-polvo",
         "helados-y-postres/helados", "licores-y-cervezas/cervezas",
         "licores-y-cervezas/hielo", "licores-y-cervezas/aguardiente",
         "licores-y-cervezas/licores-rtd", "licores-y-cervezas/whisky-blended",
         "licores-y-cervezas/whisky-single", "licores-y-cervezas/vino-tinto",
         "licores-y-cervezas/whiskys", "licores-y-cervezas/rones",
         "licores-y-cervezas/vodkas", "licores-y-cervezas/tequilas-y-mezcales",
         "licores-y-cervezas/ginebras", "licores-y-cervezas/otros-licores",
         "despensa/panaderia-dulce-tortas-y-ponques", "despensa/panaderia-salada",
         "despensa/arepas-tortillas-y-tostadas", "despensa/condimentos-salsas-y-sopas",
         "despensa/aceites-vinagres-y-conservas", "despensa/azucar-y-endulzantes",
         "despensa/cafe", "despensa/arroz-granos-y-pastas", 
         "despensa/harina-y-mezclas-para-preparar", "despensa/cereales-avenas-y-granola"
         "despensa/chocolate-infusiones-y-modificadore", "despensa/reposteria",
         "despensa/mermeladas-y-pastas-para-untar", "carnes/res",
         "carnes/pollos-y-aves", "carnes/cerdo", "carnes/pescados-y-mariscos",
         "chocolates-dulces-y-galletas/galletas", "chocolates-dulces-y-galletas/gomitas-y-caramelos",
         "chocolates-dulces-y-galletas/chocolates", "chocolates-dulces-y-galletas/dulces-tipicos",
         "chocolates-dulces-y-galletas/barras-de-cereal-y-granola", 
         "bebes/aseo-y-cuidado-del-bebe", "bebes/formulas-y-alimentos", 
         "bebes/juegos-y-accesorios", "carnes-frias/embutidos",
         "carnes-frias/charcuteria", "carnes-frias/jamones",
         "carnes-frias/salames-y-pates",
         "vinos/vino-tinto", "vinos/vino-blanco", "vinos/vino-rosado",
         "vinos/vino-espumoso", "cuidado-y-limpieza-del-hogar/cuidado-de-la-ropa",
         "cuidado-y-limpieza-del-hogar/desechables", "cuidado-y-limpieza-del-hogar/articulos-de-papel",
         "cuidado-y-limpieza-del-hogar/limpieza", "mascotas/alimento-perros",
         "mascotas/higiene-y-cuidado", "mascotas/alimento-gatos",
         "tecnologia-y-autopartes/tecnologia", "cuidado-personal/cuidado-oral",
         "cuidado-personal/desodorantes", "cuidado-personal/cuidado-del-cabello",
         "cuidado-personal/higiene-femenina", "cuidado-personal/depilacion-y-afeitado",
         "libreria/papeleria-y-oficina"
         ]
