# Generated by Django 5.1.3 on 2024-11-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='No image found', max_length=255),
            preserve_default=False,
        ),
    ]
