# Generated by Django 5.1.3 on 2024-12-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('unweighted_index', models.FloatField()),
            ],
            options={
                'db_table': 'index_prices',
            },
        ),
    ]
